"""Spec -> n8n workflow JSON.

n8n stays the scheduler and the run history; the backend stays the only place
that holds third-party credentials. So every compiled node is one of:

* a trigger (schedule / cron) and a secret webhook used by "Run now";
* an HTTP Request to  POST {AC_API_URL}/api/automations/<id>/run/<step>
  carrying the item as JSON and the installation service token;
* a fixed Code node for "Combine into one" (no user text inside it).

User-written text (messages, prompts, searches) never becomes an n8n
expression or code: it stays in the backend's copy of the spec, and n8n only
ever sends `{"input": $json}`. That rules out expression injection by design.
"""
from __future__ import annotations

from app.services.automations import catalog

ERROR_WORKFLOW_ID = "pa00errorhandler"
AC_URL = (
    "{{ (($env.AC_API_URL || '').match(/^https?:\\/\\//) ? ($env.AC_API_URL || '') : 'https://' + "
    "($env.AC_API_URL || '')).replace(/\\/+$/, '') }}"
)
COMBINE_JS = (
    "// Fixed code generated by Personal Assistant: merges the incoming items\n"
    "// into one digest item. No user input is interpolated here.\n"
    "const items = $input.all().map((i) => i.json);\n"
    "return [{ json: { items, count: items.length } }];\n"
)


def workflow_name(name: str) -> str:
    return f"PA · {name}"[:128]


def _cron(params: dict) -> str:
    hh, mm = (str(params.get("at") or "08:00").split(":") + ["0"])[:2]
    h, m = int(hh), int(mm)
    every = params.get("every") or "day"
    if every == "hour":
        return f"{m} * * * *"
    if every == "weekdays":
        return f"{m} {h} * * 1-5"
    if every == "week":
        wd = int(params.get("weekday") or 1) % 7  # 1=Mon ... 7=Sun -> cron 0=Sun
        return f"{m} {h} * * {wd}"
    return f"{m} {h} * * *"


def _http_step(name: str, node_id: str, automation_id: str, step_id: str, pos: list[int]) -> dict:
    return {
        "parameters": {
            "method": "POST",
            "url": f"={AC_URL}/api/automations/{automation_id}/run/{step_id}",
            "sendHeaders": True,
            "headerParameters": {"parameters": [{"name": "X-AC-Service-Token", "value": "={{ $env.AC_SERVICE_TOKEN }}"}]},
            "sendBody": True,
            "specifyBody": "json",
            "jsonBody": "={{ JSON.stringify({ input: $json }) }}",
            "options": {"timeout": 120000},
        },
        "id": node_id,
        "name": name,
        "type": "n8n-nodes-base.httpRequest",
        "typeVersion": 4.3,
        "position": pos,
        "retryOnFail": True,
        "maxTries": 2,
        "waitBetweenTries": 5000,
    }


def _unique(name: str, used: set[str]) -> str:
    base = name[:60]
    out, n = base, 2
    while out in used:
        out = f"{base} ({n})"
        n += 1
    used.add(out)
    return out


def compile_spec(spec: dict, *, automation_id: str, webhook_path: str) -> tuple[dict, dict[str, str]]:
    """Return (n8n workflow body, {step_id: node name}) for this spec."""
    trig = catalog.get(spec["trigger"]["block"])
    tparams = spec["trigger"].get("params") or {}
    used: set[str] = set()
    nodes: list[dict] = []
    connections: dict = {}
    names: dict[str, str] = {}
    x = 0

    def link(src: str, dst: str) -> None:
        connections.setdefault(src, {"main": [[]]})["main"][0].append({"node": dst, "type": "main", "index": 0})

    entry: list[str] = []
    if trig.key == "schedule":
        n = _unique(f"When: {trig.label.lower()}", used)
        nodes.append({"parameters": {"rule": {"interval": [{"field": "cronExpression", "expression": _cron(tparams)}]}},
                      "id": "trigger", "name": n, "type": "n8n-nodes-base.scheduleTrigger",
                      "typeVersion": 1.2, "position": [x, 0]})
        entry.append(n)
    elif trig.polling:
        minutes = int(tparams.get("every_minutes") or 5)
        n = _unique(f"Every {minutes} min", used)
        nodes.append({"parameters": {"rule": {"interval": [{"field": "minutes", "minutesInterval": minutes}]}},
                      "id": "trigger", "name": n, "type": "n8n-nodes-base.scheduleTrigger",
                      "typeVersion": 1.2, "position": [x, 0]})
        entry.append(n)

    run_now = _unique("Run now", used)
    nodes.append({"parameters": {"httpMethod": "POST", "path": webhook_path, "responseMode": "onReceived", "options": {}},
                  "id": "run-now", "name": run_now, "type": "n8n-nodes-base.webhook", "typeVersion": 2,
                  "position": [x, 200], "webhookId": webhook_path})
    entry.append(run_now)
    x += 260

    previous = entry
    if trig.polling:
        n = _unique(trig.label, used)
        nodes.append(_http_step(n, "fetch", automation_id, "trigger", [x, 100]))
        names["trigger"] = n
        for e in previous:
            link(e, n)
        previous = [n]
        x += 260

    for i, step in enumerate(spec["steps"], start=1):
        block = catalog.get(step["block"])
        n = _unique(f"{i}. {step.get('label') or block.label}", used)
        names[step["id"]] = n
        if block.key == "transform.combine":
            nodes.append({"parameters": {"jsCode": COMBINE_JS}, "id": f"step-{step['id']}", "name": n,
                          "type": "n8n-nodes-base.code", "typeVersion": 2, "position": [x, 100]})
        else:
            nodes.append(_http_step(n, f"step-{step['id']}", automation_id, step["id"], [x, 100]))
        for e in previous:
            link(e, n)
        previous = [n]
        x += 260

    body = {
        "name": workflow_name(spec["name"]),
        "nodes": nodes,
        "connections": connections,
        "settings": {
            "executionOrder": "v1",
            "saveManualExecutions": True,
            "saveDataErrorExecution": "all",
            "saveDataSuccessExecution": "all",
            "callerPolicy": "workflowsFromSameOwner",
            "errorWorkflow": ERROR_WORKFLOW_ID,
        },
    }
    return body, names
